### ISSUE TITLE
Support Expo

### ISSUE THREAD

**Issue by ferndot** [khorark/svg2rn#1]
For Expo SVG generation, just a few things need to be different. I am hoping this could be added as a CLI argument. Something like `svg2rn --expo` would work wonderfully.

The import:
```python
import Svg from "expo";
```

The components: `Circle`, `Rect`, `Path`, etc should be prefixed with `Svg.`: `Svg.Circle`, `Svg.Rect`, `Svg.Path`

**Comment by khorark** [comment]
> For Expo SVG generation, just a few things need to be different. I am hoping this could be added as a CLI argument. Something like `svg2rn --expo` would work wonderfully.
> 
> The import:
> 
> ```python
> import Svg from "expo";
> ```
> 
> The components: `Circle`, `Rect`, `Path`, etc should be prefixed with `Svg.`: `Svg.Circle`, `Svg.Rect`, `Svg.Path`

**Comment by khorark** [comment]
Please update version to 1.5.1 and let me know the results. 

Thank you feedback.

**Comment by ferndot** [comment]
This works perfectly, thank you! You did this sooo fast.
