### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by ddaeschler** [khorark/svg2rn#7]
I've used this library on a few SVG files so far and I've had very good results. Thank you so much! I've needed native SVG support for rescaling and colorization and this library does it.

One thing that would be nice is to have a typescript output mode. Currently, we're developing a react native application in typescript, and having the autocompletion help is a huge benefit.

Only a couple of things would need to change to support this that I can see:

- Change output extension from .js to .tsx
- add SvgProps to import:  import Svg, { G, Path, SvgProps } from "react-native-svg"
- Add the SvgProps type to the generated JSX object: 
```
const Logo = (props: SvgProps) => (
  <Svg width={66} ...
```

Thanks very much for this library

**Comment by khorark** [comment]
Thank you for what use this library, it's very nice!

I upgraded version to **1.9.1** and added support typescript. For use write flag **--ts**. 

Please updated your version and check that.
